import Head from 'next/head';
import { Page } from '@/components/Shared/Page';
import { useGetUser } from '@/features/_queries_/_rest_api_';
import { useEffect } from 'react';
import { useRouter } from 'next/router';
import Main from '@/components/Main';
import BottomTabs from '@/components/Shared/BottomTabs';
import Loader from '@/components/Shared/Loader';

export default function Home() {
  const router = useRouter();
  const { loading, data, error } = useGetUser();
  console.log(data);
  useEffect(() => {
    if (error) {
      console.log(error);
      router.push('/new_person');
    }
  }, [error]);

  return (
    <>
      <Head>
        <title>Kvaks</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Page back={false}>
        <main>
          {loading ? (
            <Loader />
          ) : error ? (
            <>error</>
          ) : (
            data && (
              <>
                <Main data={data} />

                <BottomTabs
                  play={
                    // @ts-ignore
                    data?.last_section_slug
                      ? // @ts-ignore
                        `/courses/rossijskoe-gostepriimstvo/${data?.last_section_slug}`
                      : '/courses/rossijskoe-gostepriimstvo'
                  }
                />
              </>
            )
          )}
        </main>
      </Page>
    </>
  );
}
